# Generated by Django 6.0 on 2026-01-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_productoacademico_url_recurso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencialaboral',
            name='rutacertificado',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
