# Generated by Django 6.0 on 2026-01-23 00:29

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_alter_experiencialaboral_rutacertificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventagarage',
            name='fechapublicacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ventagarage',
            name='foto_producto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto_producto'),
        ),
    ]
