# Generated by Django 6.0 on 2026-01-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_ventagarage_fechapublicacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventagarage',
            name='foto_producto',
        ),
        migrations.AddField(
            model_name='ventagarage',
            name='url_foto_producto',
            field=models.URLField(blank=True, help_text='Pega aquí el link de la imagen subida en Cloudinary', null=True),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='fechapublicacion',
            field=models.DateField(),
        ),
    ]
