# Generated by Django 6.0 on 2026-01-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_remove_ventagarage_foto_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_cursos_realizados',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_experiencia_laboral',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_productos_academicos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_productos_laborales',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_reconocimientos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_venta_garage',
            field=models.BooleanField(default=True),
        ),
    ]
