# Generated by Django 6.0 on 2026-01-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursorealizado',
            name='certificado',
        ),
        migrations.AddField(
            model_name='cursorealizado',
            name='rutacertificado',
            field=models.URLField(blank=True, null=True),
        ),
    ]
