# Generated by Django 6.0 on 2026-01-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_remove_cursorealizado_certificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoacademico',
            name='url_recurso',
            field=models.URLField(blank=True, null=True, verbose_name='URL del recurso (Cloudinary)'),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='rutacertificado',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
